#!/bin/bash
dir=$(dirname $(readlink -f ${0}))
. ${dir}/.k8s-cfg/functions

if (( rename )); then
    name=${id}${name}
fi
expr="(creationTimestamp|generation|resourceVersion|selfLink|uid|terminationMessagePath|observedGeneration)"
kubectl get rc ${name} --namespace=${namespace} --output=yaml|\
    grep -vE "^ *${expr}" | tee ${name}.tmp.cluster.yaml | yaml2json > ${name}.tmp.cluster.json
